[package]
name = "snek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
fastrand = "1.6.0"
iyes_loopless = "0.7"
